name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Publish
      run: |
        echo "//registry.npmjs.org/:_authToken=${secrets.REGISTRY_TOKEN}" > ./.npmrc
        npm publish --access=public
      