name: Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      id: autotagger
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    